version: "3"

services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
      POSTGRES_USER: ${KEYCLOAK_PG_USER:-keycloak}
      POSTGRES_DB: ${KEYCLOAK_PG_DB:-keycloak}

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  fuseki:
    build:
      context: .
      dockerfile: Dockerfile.fuseki
      args:
        FUSEKI_VERSION: 4.0.0
    restart: always
    volumes:
      - fuseki_data:/fuseki
      - ./data.ttl:/fuseki/configuration/data.ttl:ro
      - ./inf_cache.ttl:/fuseki/configuration/inf_cache.ttl:ro
    environment:
      ADMIN_PASSWORD: ${FUSEKI_ADMIN_PASSWORD}
      JVM_ARGS: ${JVM_ARGS:--Xmx2g}
      TDB: 2

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    restart: always
    environment:
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_PG_DB:-keycloak}
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
      DB_SCHEMA: public
      DB_USER: ${KEYCLOAK_PG_USER:-keycloak}
      DB_VENDOR: POSTGRES
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_FRONTEND_URL}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPLICATION_PORT: ${APPLICATION_PORT:-8080}
        CORE_OWL_URL: https://purl.org/nampi/owl/core
        DATA_BASE_URL: ${DATA_BASE_URL}
        DATA_URL: http://fuseki:3030/data
        DEFAULT_LIMIT: ${DEFAULT_LIMIT:-20}
        INF_CACHE_URL: http://fuseki:3030/inf_cache
        JAVA_VERSION: 11
        KEYCLOAK_RDF_ID_ATTRIBUTE: ${KEYCLOAK_RDF_ID_ATTRIBUTE:-rdf-id}
        KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
        KEYCLOAK_URL: http://keycloak:8080/auth
        LOGGING_LEVEL: ${LOGGING_LEVEL:-INFO}
        OTHER_OWL_URLS: ${OTHER_OWL_URLS}
        PROFILE: ${PROFILE:-prod}
        REDIS_PORT: ${REDIS_PORT:-6379}
        REDIS_URL: ${REDIS_URL:-redis}
    restart: always
    depends_on:
      - keycloak
      - fuseki
      - redis

volumes:
  keycloak_data: {}
  fuseki_data: {}
  redis_data: {}
