version: "3"

services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
      POSTGRES_USER: ${KEYCLOAK_PG_USER:-keycloak}
      POSTGRES_DB: ${KEYCLOAK_PG_DB:-keycloak}

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  fuseki:
    build:
      context: .
      dockerfile: Dockerfile.fuseki
      args:
        FUSEKI_VERSION: 3.14.0
    restart: always
    volumes:
      - fuseki_data:/fuseki
      - ./nampi.ttl:/fuseki/configuration/nampi.ttl:ro
    environment:
      ADMIN_PASSWORD: ${FUSEKI_ADMIN_PASSWORD}
      JVM_ARGS: ${JVM_ARGS:-Xmx2g}
      TDB: 2
      FUSEKI_DATASET: ${DATASET_NAME:-data}

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_PG_DB:-keycloak}
      DB_USER: ${KEYCLOAK_PG_USER:-keycloak}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_PG_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: 11
        KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
        KEYCLOAK_URL: http://keycloak:8080/auth
        LOGGING_LEVEL: ${LOGGING_LEVEL:-DEBUG}
        OTHER_OWL_URLS: ${OTHER_OWL_URLS}
        PROFILE: ${PROFILE:-prod}
        TRIPLE_STORE_URL: http://fuseki:3030/${DATASET_NAME:-nampi}
        REDIS_URL: redis
    restart: always
    depends_on:
      - keycloak
      - fuseki
      - redis

volumes:
  keycloak_data: {}
  fuseki_data: {}
  redis_data: {}
