keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  principal-attribute: preferred_username
  public-client: true
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  bearer-only: true

logging:
  level:
    org:
      springframework:
        web: ${LOGGING_LEVEL:INFO} 

nampi:
  triple-store-url: ${TRIPLE_STORE_URL} 
  core-owl-url: ${CORE_OWL_URL:https://purl.org/nampi/owl/core}
  other-owl-urls: ${OTHER_OWL_URLS:}

server:
  port: ${APPLICATION_PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true
