keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  principal-attribute: preferred_username
  public-client: true
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  bearer-only: true

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    org:
      apache:
        http:
          wire: WARN

nampi:
  core-owl-url: ${CORE_OWL_URL:https://purl.org/nampi/owl/core}
  dataset-url-data: ${DATA_URL}
  dataset-url-inf-cache: ${INF_CACHE_URL}
  default-limit: ${DEFAULT_LIMIT:25}
  keycloak-rdf-id-attribute: ${KEYCLOAK-RDF-ID-ATTRIBUTE:rdf-id}
  individuals-base-url: ${INDIVIDUALS_BASE_URL}
  other-owl-urls: ${OTHER_OWL_URLS:}

server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  cache:
    type: redis
    cache-names:
      - events
      - persons
      - aspects
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE:prod}
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
