keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  principal-attribute: preferred_username
  public-client: true
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  bearer-only: true

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    org:
      apache:
        http:
          wire: WARN

nampi:
  core-owl-url: ${CORE_OWL_URL:http://purl.org/nampi/owl/core}
  data-base-url: ${DATA_BASE_URL:}
  dataset-url-data: ${DATA_URL}
  dataset-url-inf-cache: ${INF_CACHE_URL}
  default-limit: ${DEFAULT_LIMIT:20}
  keycloak-rdf-id-attribute: ${KEYCLOAK-RDF-ID-ATTRIBUTE:rdf-id}
  other-owl-urls: ${OTHER_OWL_URLS:}
  crm-prefix: http://erlangen-crm.org/211015/

server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true
  http2:
    enabled: true
  error:
    include-stacktrace: Never

spring:
  cache:
    type: redis
    cache-names:
      - acts
      - aspects
      - authors
      - events
      - groups
      - hierarchies
      - jena
      - persons
      - places
      - sources
      - types
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE:prod}
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
