keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  principal-attribute: preferred_username
  public-client: true
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  bearer-only: true

logging:
  level:
    org:
      springframework:
        web: ${LOGGING_LEVEL:INFO} 

nampi:
  default-limit: ${DEFAULT_LIMIT:25}
  core-owl-url: ${CORE_OWL_URL:https://purl.org/nampi/owl/core}
  other-owl-urls: ${OTHER_OWL_URLS:}
  triple-store-url: ${TRIPLE_STORE_URL} 

server:
  port: ${APPLICATION_PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT:6379}
